# Logging
# 	level can be an integer between 1 and 3.
# 	1	-> Debug
# 	2	-> Info
# 	3	-> Warning
logLevel = 1

# Absolute path to the database
database = "example.bolt"

# The runtime directory used for creating sockets
runtimeDirectory = "/tmp"

# Temporary directory to host cache produced by daemon
temporaryDirectory = "/tmp/123456"